name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the project with a clean slate
        run: echo "npm clean install"
      - name: "Build the package"
        run: echo "npm run build --if-present"
      - name: Run the automated tests
        run: |
          echo "npm test"
          echo "100% tests pass - yay!"
